"""
Integration tests verifying that :class:`~yobx.builder.onnxscript.OnnxScriptGraphBuilder`
produces ONNX models equivalent to those generated by the yobx sklearn converter
(:func:`yobx.sklearn.to_onnx`).

For each supported sklearn estimator, the test:

1. Fits the estimator on a small dataset.
2. Converts it to ONNX via ``yobx.sklearn.to_onnx`` (uses the yobx ``GraphBuilder``).
3. Manually recreates an equivalent ONNX model using ``OnnxScriptGraphBuilder``.
4. Runs both models through ``onnx.reference.ExtendedReferenceEvaluator`` and asserts
   numerical equivalence.

This confirms that the two builder paths produce interchangeable graphs.
"""

import unittest
import numpy as np
import onnx
from yobx.ext_test_case import ExtTestCase, requires_onnxscript, requires_sklearn
from yobx.helpers.onnx_helper import _default_OPSET_TO_IR_VERSION
from yobx.reference import ExtendedReferenceEvaluator


@requires_sklearn("1.4")
@requires_onnxscript()
class TestOnnxScriptBridgeWithSklearnConverter(ExtTestCase):
    def _make_builder(self, opset: int = 18):
        from yobx.builder.onnxscript import OnnxScriptGraphBuilder

        return OnnxScriptGraphBuilder(opset)

    def _ref_run(self, proto, inputs: dict):
        ref = ExtendedReferenceEvaluator(proto)
        return ref.run(None, inputs)

    def test_standard_scaler_valid_onnx(self):
        from sklearn.preprocessing import StandardScaler
        from yobx.sklearn import to_onnx

        X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=np.float32)
        ss = StandardScaler()
        ss.fit(X)

        onx = to_onnx(ss, (X,))

        op_types = [n.op_type for n in onx.graph.node]
        self.assertIn("Sub", op_types)
        self.assertIn("Div", op_types)

    def test_standard_scaler_manual_vs_converter(self):
        """OnnxScriptGraphBuilder replicates StandardScaler output."""
        from sklearn.preprocessing import StandardScaler
        from yobx.sklearn import to_onnx

        X = np.array([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0], [7.0, 8.0]], dtype=np.float32)
        ss = StandardScaler()
        ss.fit(X)
        expected = ss.transform(X).astype(np.float32)

        # --- Reference: yobx sklearn converter ---
        onx_ref = to_onnx(ss, (X,))
        (result_ref,) = self._ref_run(onx_ref, {"X": X})

        # --- OnnxScriptGraphBuilder replica ---
        gr = self._make_builder()
        gr.make_tensor_input("X", onnx.TensorProto.FLOAT, ("batch", 2))
        mean_name = gr.make_initializer("mean", ss.mean_.astype(np.float32))
        scale_name = gr.make_initializer("scale", ss.scale_.astype(np.float32))
        centered = gr.make_node("Sub", ["X", mean_name], "centered")
        _output = gr.make_node("Div", [centered, scale_name], "Y")
        gr.make_tensor_output("Y", onnx.TensorProto.FLOAT)
        proto = gr.to_onnx()

        onnx.checker.check_model(proto)
        (result_bridge,) = self._ref_run(proto, {"X": X})

        self.assertEqualArray(expected, result_ref, atol=1e-5)
        self.assertEqualArray(expected, result_bridge, atol=1e-5)

    def test_standard_scaler_no_mean(self):
        """OnnxScriptGraphBuilder handles StandardScaler with_mean=False."""
        from sklearn.preprocessing import StandardScaler

        X = np.array([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]], dtype=np.float32)
        ss = StandardScaler(with_mean=False)
        ss.fit(X)
        expected = ss.transform(X).astype(np.float32)

        gr = self._make_builder()
        gr.make_tensor_input("X", onnx.TensorProto.FLOAT, ("batch", 2))
        scale_name = gr.make_initializer("scale", ss.scale_.astype(np.float32))
        gr.make_node("Div", ["X", scale_name], "Y")
        gr.make_tensor_output("Y", onnx.TensorProto.FLOAT)
        proto = gr.to_onnx()

        onnx.checker.check_model(proto)
        (result,) = self._ref_run(proto, {"X": X})
        self.assertEqualArray(expected, result, atol=1e-5)

    def test_standard_scaler_no_std(self):
        """OnnxScriptGraphBuilder handles StandardScaler with_std=False."""
        from sklearn.preprocessing import StandardScaler

        X = np.array([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]], dtype=np.float32)
        ss = StandardScaler(with_std=False)
        ss.fit(X)
        expected = ss.transform(X).astype(np.float32)

        gr = self._make_builder()
        gr.make_tensor_input("X", onnx.TensorProto.FLOAT, ("batch", 2))
        mean_name = gr.make_initializer("mean", ss.mean_.astype(np.float32))
        gr.make_node("Sub", ["X", mean_name], "Y")
        gr.make_tensor_output("Y", onnx.TensorProto.FLOAT)
        proto = gr.to_onnx()

        onnx.checker.check_model(proto)
        (result,) = self._ref_run(proto, {"X": X})
        self.assertEqualArray(expected, result, atol=1e-5)

    # ------------------------------------------------------------------
    # LogisticRegression (binary)
    # ------------------------------------------------------------------

    def test_logistic_regression_binary_valid_onnx(self):
        """yobx sklearn converter produces ONNX with the expected Gemm node for binary LR."""
        from sklearn.linear_model import LogisticRegression
        from yobx.sklearn import to_onnx

        X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=np.float32)
        y = np.array([0, 0, 1, 1])
        lr = LogisticRegression()
        lr.fit(X, y)

        onx = to_onnx(lr, (X,))

        op_types = [n.op_type for n in onx.graph.node]
        self.assertIn("Gemm", op_types)

    def test_logistic_regression_binary_manual_vs_converter(self):
        """OnnxScriptGraphBuilder replicates binary LogisticRegression output."""
        from sklearn.linear_model import LogisticRegression
        from yobx.sklearn import to_onnx

        X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=np.float32)
        y = np.array([0, 0, 1, 1])
        lr = LogisticRegression()
        lr.fit(X, y)

        coef = lr.coef_.astype(np.float32)
        intercept = lr.intercept_.astype(np.float32)

        # Reference via yobx converter
        onx_ref = to_onnx(lr, (X,))
        results_ref = self._ref_run(onx_ref, {"X": X})
        label_ref, proba_ref = results_ref[0], results_ref[1]

        # OnnxScriptGraphBuilder replica: Gemm → Sigmoid → Concat → ArgMax → Gather
        gr = self._make_builder()
        gr.make_tensor_input("X", onnx.TensorProto.FLOAT, ("batch", 2))
        coef_name = gr.make_initializer("coef", coef)
        intercept_name = gr.make_initializer("intercept", intercept)

        decision = gr.make_node("Gemm", ["X", coef_name, intercept_name], "decision", transB=1)
        proba_pos = gr.make_node("Sigmoid", [decision], "proba_pos")
        one = gr.make_initializer("one", np.array([1.0], dtype=np.float32))
        proba_neg = gr.make_node("Sub", [one, proba_pos], "proba_neg")
        proba = gr.make_node("Concat", [proba_neg, proba_pos], "probabilities", axis=-1)

        label_idx = gr.make_node("ArgMax", [proba], "label_idx", axis=1, keepdims=0)
        label_idx_64 = gr.make_node(
            "Cast", [label_idx], "label_idx_64", to=onnx.TensorProto.INT64
        )
        classes = gr.make_initializer("classes", lr.classes_.astype(np.int64))
        _label = gr.make_node("Gather", [classes, label_idx_64], "label", axis=0)

        gr.make_tensor_output("label", onnx.TensorProto.INT64)
        gr.make_tensor_output("probabilities", onnx.TensorProto.FLOAT)
        proto = gr.to_onnx()

        onnx.checker.check_model(proto)
        results_bridge = self._ref_run(proto, {"X": X})
        label_bridge, proba_bridge = results_bridge[0], results_bridge[1]

        self.assertEqualArray(label_ref, label_bridge)
        self.assertEqualArray(proba_ref, proba_bridge, atol=1e-5)

    # ------------------------------------------------------------------
    # LogisticRegression (multiclass)
    # ------------------------------------------------------------------

    def test_logistic_regression_multiclass_valid_onnx(self):
        """yobx sklearn converter produces ONNX with Gemm and Softmax for multiclass LR."""
        from sklearn.linear_model import LogisticRegression
        from yobx.sklearn import to_onnx

        X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [2, 3], [4, 5]], dtype=np.float32)
        y = np.array([0, 0, 1, 1, 2, 2])
        lr = LogisticRegression(max_iter=200)
        lr.fit(X, y)

        onx = to_onnx(lr, (X,))

        op_types = [n.op_type for n in onx.graph.node]
        self.assertIn("Gemm", op_types)
        self.assertIn("Softmax", op_types)

    def test_logistic_regression_multiclass_manual_vs_converter(self):
        """OnnxScriptGraphBuilder replicates multiclass LogisticRegression output."""
        from sklearn.linear_model import LogisticRegression
        from yobx.sklearn import to_onnx

        X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [2, 3], [4, 5]], dtype=np.float32)
        y = np.array([0, 0, 1, 1, 2, 2])
        lr = LogisticRegression(max_iter=200)
        lr.fit(X, y)

        coef = lr.coef_.astype(np.float32)
        intercept = lr.intercept_.astype(np.float32)

        # Reference via yobx converter
        onx_ref = to_onnx(lr, (X,))
        results_ref = self._ref_run(onx_ref, {"X": X})

        # OnnxScriptGraphBuilder replica: Gemm → Softmax → ArgMax → Gather
        gr = self._make_builder()
        gr.make_tensor_input("X", onnx.TensorProto.FLOAT, ("batch", 2))
        coef_name = gr.make_initializer("coef", coef)
        intercept_name = gr.make_initializer("intercept", intercept)

        decision = gr.make_node("Gemm", ["X", coef_name, intercept_name], "decision", transB=1)
        proba = gr.make_node("Softmax", [decision], "probabilities", axis=1)
        label_idx = gr.make_node("ArgMax", [proba], "label_idx", axis=1, keepdims=0)
        label_idx_64 = gr.make_node(
            "Cast", [label_idx], "label_idx_64", to=onnx.TensorProto.INT64
        )
        classes = gr.make_initializer("classes", lr.classes_.astype(np.int64))
        _label = gr.make_node("Gather", [classes, label_idx_64], "label", axis=0)

        gr.make_tensor_output("label", onnx.TensorProto.INT64)
        gr.make_tensor_output("probabilities", onnx.TensorProto.FLOAT)
        proto = gr.to_onnx()

        onnx.checker.check_model(proto)
        results_bridge = self._ref_run(proto, {"X": X})

        self.assertEqualArray(results_ref[0], results_bridge[0])
        self.assertEqualArray(results_ref[1], results_bridge[1], atol=1e-5)

    def test_to_ir_dtype_float(self):
        from yobx.builder.onnxscript.bridge_graph_builder import to_ir_dtype
        import onnx_ir as ir

        dtype = to_ir_dtype(onnx.TensorProto.FLOAT)
        self.assertEqual(dtype, ir.DataType.FLOAT)

    def test_to_ir_dtype_none(self):
        from yobx.builder.onnxscript.bridge_graph_builder import to_ir_dtype

        self.assertIsNone(to_ir_dtype(None))
        self.assertIsNone(to_ir_dtype(0))

    def test_to_ir_shape_static(self):
        from yobx.builder.onnxscript.bridge_graph_builder import to_ir_shape
        import onnx_ir as ir

        shape = to_ir_shape((2, 4))
        self.assertIsInstance(shape, ir.Shape)

    def test_to_ir_shape_dynamic(self):
        from yobx.builder.onnxscript.bridge_graph_builder import to_ir_shape
        import onnx_ir as ir

        shape = to_ir_shape(("batch", None, 4))
        self.assertIsInstance(shape, ir.Shape)

    def test_to_ir_shape_none(self):
        from yobx.builder.onnxscript.bridge_graph_builder import to_ir_shape

        self.assertIsNone(to_ir_shape(None))

    def test_value_to_ir_tensor_ndarray(self):
        from yobx.builder.onnxscript.bridge_graph_builder import value_to_ir_tensor

        arr = np.ones((3, 4), dtype=np.float32)
        t = value_to_ir_tensor(arr, "W")
        self.assertIsNotNone(t)

    def test_value_to_ir_tensor_int_scalar(self):
        from yobx.builder.onnxscript.bridge_graph_builder import value_to_ir_tensor

        t = value_to_ir_tensor(42, "x")
        self.assertIsNotNone(t)

    def test_value_to_ir_tensor_float_scalar(self):
        from yobx.builder.onnxscript.bridge_graph_builder import value_to_ir_tensor

        t = value_to_ir_tensor(3.14, "x")
        self.assertIsNotNone(t)

    def test_value_to_ir_tensor_tensor_proto(self):
        from onnx import numpy_helper
        from yobx.builder.onnxscript.bridge_graph_builder import value_to_ir_tensor

        tp = numpy_helper.from_array(np.array([1.0, 2.0], dtype=np.float32), name="v")
        t = value_to_ir_tensor(tp, "v")
        self.assertIsNotNone(t)

    def test_value_to_ir_tensor_unsupported_raises(self):
        from yobx.builder.onnxscript.bridge_graph_builder import value_to_ir_tensor

        with self.assertRaises(TypeError):
            value_to_ir_tensor("not_a_tensor", "bad")

    def test_default_ir_version_known_opset(self):
        self.assertEqual(_default_OPSET_TO_IR_VERSION()[18], 8)
        self.assertEqual(_default_OPSET_TO_IR_VERSION()[21], 10)

    def test_pipeline_standard_scaler_logistic_regression(self):
        from sklearn.preprocessing import StandardScaler
        from sklearn.linear_model import LogisticRegression
        from sklearn.pipeline import Pipeline
        from yobx.sklearn import to_onnx
        from yobx.builder.onnxscript import OnnxScriptGraphBuilder

        X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=np.float32)
        y = np.array([0, 0, 1, 1])
        pipe = Pipeline([("scaler", StandardScaler()), ("clf", LogisticRegression())])
        pipe.fit(X, y)

        onx = to_onnx(pipe, (X,), builder_cls=OnnxScriptGraphBuilder)
        self.dump_onnx("test_pipeline_standard_scaler_logistic_regression.onnx", onx)

        # Check graph contains nodes from both steps
        op_types = [n.op_type for n in onx.graph.node]
        self.assertIn("Sub", op_types)
        self.assertIn("Div", op_types)
        self.assertIn("Gemm", op_types)

        # Check outputs
        ref = ExtendedReferenceEvaluator(onx)
        results = ref.run(None, {"X": X})
        label, proba = results[0], results[1]

        self.assertEqualArray(pipe.predict(X), label)
        self.assertEqualArray(pipe.predict_proba(X).astype(np.float32), proba, atol=1e-5)


if __name__ == "__main__":
    unittest.main(verbosity=2)
