"""
Validates an ONNX export for a HuggingFace model using
:class:`InputObserver <yobx.torch.InputObserver>` and a default text prompt.

Unlike :func:`onnx_diagnostic.torch_models.validate.validate_model`, which uses
random/dummy tensors as inputs, this module captures real model inputs by running the
model on a default prompt through an :class:`InputObserver`.  The observed inputs and
inferred dynamic shapes are then used for the ONNX export.
"""

import contextlib
from typing import Any, Dict, Optional, Tuple
import os

DEFAULT_PROMPT = "Continue: it rains, what should I do?"
"""Default text prompt used when validating text-generation models."""


def validate_model(
    model_id: str,
    prompt: str = DEFAULT_PROMPT,
    exporter: str = "yobx",
    optimization: Optional[str] = "default",
    verbose: int = 0,
    dump_folder: Optional[str] = None,
    opset: int = 18,
    dtype: Optional[str] = None,
    device: Optional[str] = None,
    max_new_tokens: int = 10,
    do_run: bool = True,
    patch: bool = True,
    quiet: bool = False,
) -> Tuple[Dict[str, Any], Dict[str, Any]]:
    """
    Validates an ONNX export for any HuggingFace ``model_id`` by capturing real
    model inputs with :class:`InputObserver <yobx.torch.InputObserver>` and a
    text *prompt*, instead of relying on dummy / random tensors.

    The function:

    1. Loads the pretrained model and tokeniser for *model_id* from HuggingFace.
    2. Runs :meth:`model.generate` with *prompt* inside an
       :class:`InputObserver <yobx.torch.InputObserver>` context to collect
       real input/output tensors.
    3. Exports the model to ONNX using the observed inputs and the inferred
       dynamic shapes.
    4. Computes discrepancies between the original PyTorch outputs and the
       ONNX runtime outputs for every captured input set.

    :param model_id: HuggingFace model id, e.g. ``"arnir0/Tiny-LLM"``
    :param prompt: Text prompt used to drive the generation step.
        Defaults to :data:`DEFAULT_PROMPT`.
    :param exporter: ONNX exporter to use, e.g. ``"yobx"`` (default),
        ``"onnx-dynamo"``, or ``"modelbuilder"``.
    :param optimization: Optimisation level applied after export.
        Passed directly to :func:`yobx.torch.to_onnx`.  ``None`` means no
        optimisation; ``"default"`` applies the default set.
    :param verbose: Verbosity level (0 = silent).
    :param dump_folder: When given, all artefacts (ONNX file, export logs …)
        are saved under this directory.
    :param opset: ONNX opset version to target (default 18).
    :param dtype: Cast the model (and inputs) to this dtype before exporting,
        e.g. ``"float16"``.  ``None`` keeps the default (``float32``).
    :param device: Run on this device, e.g. ``"cpu"`` or ``"cuda"``.
        ``None`` defaults to CPU.
    :param max_new_tokens: Number of tokens generated by
        :meth:`model.generate` during input capture (default 10).
        Larger values capture more past-key-value shapes.
    :param do_run: When ``True`` (default), checks that the ONNX model can be
        run after export and computes discrepancies.
    :param patch: Apply ``apply_patches_for_model`` and
        ``register_flattening_functions`` during export (default ``True``).
    :param quiet: When ``True``, exceptions are caught and reported in the
        returned summary dictionary rather than re-raised.
    :return: A 2-tuple ``(summary, data)`` where *summary* is a flat
        ``{str: value}`` dictionary suitable for display or logging, and
        *data* collects all intermediate artefacts.

    Example::

        from yobx.torch.validate import validate_model

        summary, data = validate_model("arnir0/Tiny-LLM", verbose=1)
        for k, v in sorted(summary.items()):
            print(f":{k},{v};")
    """
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer

    from .flatten import register_flattening_functions
    from .input_observer import InputObserver
    from .interpreter import to_onnx
    from .patch import apply_patches_for_model

    summary: Dict[str, Any] = {"model_id": model_id, "prompt": prompt}
    collected_data: Dict[str, Any] = {}

    # ------------------------------------------------------------------ device
    torch_device = torch.device(device or "cpu")

    # ----------------------------------------------------------------- dtype
    torch_dtype: Optional[torch.dtype] = None
    if dtype is not None:
        torch_dtype = getattr(torch, dtype)

    # --------------------------------------------------------------- load model
    if verbose:
        print(f"[validate_model] loading tokenizer for {model_id!r}")

    try:
        tokenizer = AutoTokenizer.from_pretrained(model_id)
    except Exception as exc:
        summary["error_tokenizer"] = str(exc)
        if not quiet:
            raise
        return summary, collected_data

    if verbose:
        print(f"[validate_model] loading model for {model_id!r}")

    try:
        model: torch.nn.Module = AutoModelForCausalLM.from_pretrained(
            model_id,
            **({"torch_dtype": torch_dtype} if torch_dtype is not None else {}),
        )
        model = model.to(torch_device)
        model.eval()
    except Exception as exc:
        summary["error_model"] = str(exc)
        if not quiet:
            raise
        return summary, collected_data

    collected_data["model"] = model

    # ---------------------------------------------------------- tokenise prompt
    inputs = tokenizer(prompt, return_tensors="pt")
    input_ids = inputs["input_ids"].to(torch_device)
    attention_mask = inputs["attention_mask"].to(torch_device)

    collected_data["input_ids"] = input_ids
    collected_data["attention_mask"] = attention_mask

    # ------------------------------------------------------- capture with observer
    if verbose:
        print(f"[validate_model] capturing inputs with InputObserver (prompt={prompt!r})")

    observer = InputObserver()

    try:
        with (
            register_flattening_functions(patch_transformers=patch),
            apply_patches_for_model(patch_transformers=patch, model=model) if patch else contextlib.nullcontext(),
            observer(model),
        ):
            model.generate(
                input_ids=input_ids,
                attention_mask=attention_mask,
                do_sample=False,
                max_new_tokens=max_new_tokens,
            )
    except Exception as exc:
        summary["error_observer"] = str(exc)
        if not quiet:
            raise
        return summary, collected_data

    collected_data["observer"] = observer
    summary["n_captured"] = len(observer.info)

    if verbose:
        print(f"[validate_model] captured {len(observer.info)} input set(s)")

    # ---------------------------------------------------- infer args & shapes
    with register_flattening_functions(patch_transformers=patch):
        kwargs = observer.infer_arguments()
        dynamic_shapes = observer.infer_dynamic_shapes(set_batch_dimension_for=True)

    collected_data["kwargs"] = kwargs
    collected_data["dynamic_shapes"] = dynamic_shapes

    if verbose:
        from ..helpers import string_type

        print(f"[validate_model] kwargs: {string_type(kwargs, with_shape=True)}")
        print(f"[validate_model] dynamic_shapes: {dynamic_shapes}")

    # ------------------------------------------------------------------- export
    if dump_folder is not None:
        os.makedirs(dump_folder, exist_ok=True)
        model_name = model_id.replace("/", "-")
        filename = os.path.join(dump_folder, f"{model_name}.onnx")
    else:
        import tempfile

        _tmpdir = tempfile.mkdtemp()
        model_name = model_id.replace("/", "-")
        filename = os.path.join(_tmpdir, f"{model_name}.onnx")

    collected_data["filename"] = filename

    if verbose:
        print(f"[validate_model] exporting to ONNX ({exporter=}, {opset=}) -> {filename!r}")

    try:
        export_kwargs: Dict[str, Any] = {}
        if optimization is not None:
            export_kwargs["optimization"] = optimization

        with (
            register_flattening_functions(patch_transformers=patch),
            apply_patches_for_model(
                patch_torch=patch, patch_transformers=patch, model=model
            ) if patch else contextlib.nullcontext(),
        ):
            to_onnx(
                model,
                (),
                kwargs=kwargs,
                dynamic_shapes=dynamic_shapes,
                filename=filename,
                exporter=exporter,
                opset_version=opset,
                verbose=max(0, verbose - 1),
                **export_kwargs,
            )
        summary["export"] = "OK"
    except Exception as exc:
        summary["export"] = "FAILED"
        summary["error_export"] = str(exc)
        if not quiet:
            raise
        return summary, collected_data

    if verbose:
        print(f"[validate_model] export succeeded -> {filename!r}")

    # --------------------------------------------------------- check discrepancies
    if do_run:
        if verbose:
            print("[validate_model] checking discrepancies ...")
        try:
            disc_data = observer.check_discrepancies(filename)
            collected_data["discrepancies"] = disc_data
            n_ok = sum(1 for row in disc_data if row.get("SUCCESS", False))
            n_total = len(disc_data)
            summary["discrepancies_ok"] = n_ok
            summary["discrepancies_total"] = n_total
            summary["discrepancies"] = "OK" if n_ok == n_total else "FAILED"
            if verbose:
                print(f"[validate_model] discrepancies: {n_ok}/{n_total} OK")
        except Exception as exc:
            summary["discrepancies"] = "FAILED"
            summary["error_discrepancies"] = str(exc)
            if not quiet:
                raise

    return summary, collected_data
