name: ci-3-imbalanced-learn

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 5 * * *"

jobs:
  imblearn_tests:
    name: imblearn (ubuntu-latest, py3.12, sklearn-${{ matrix.sklearn-version }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        sklearn-version: ["1.4", "1.8"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -e ".[dev,imblearn,sklearn]"

      - name: Install scikit-learn==${{ matrix.sklearn-version }}
        run: pip install "scikit-learn==${{ matrix.sklearn-version }}.*" && pip freeze

      - name: pip freeze
        run: pip freeze

      - name: Run imblearn tests with no coverage
        if: matrix.sklearn-version != '1.8'
        run: |
          cd unittests/sklearn/_imblearn
          python -m unittest discover -v

      - name: Run unittest files with coverage, not pytest
        if: matrix.sklearn-version == '1.8'
        run: |
          cd unittests/sklearn/_imblearn
          coverage run -m unittest discover -v
          coverage xml
          cp *.xml ../../..
          cd ../../..

      - name: Upload coverage to Codecov
        if: matrix.sklearn-version == '1.8'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: imblearn
