name: ci-2

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 4 * * *"

jobs:
  sklearn_tests:
    name: sklearn (ubuntu-latest, py3.12, sklearn-${{ matrix.sklearn-version }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        sklearn-version: ["1.4", "1.8"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -e ".[dev,sklearn]"

      - name: Install scikit-learn==${{ matrix.sklearn-version }}
        run: pip install "scikit-learn==${{ matrix.sklearn-version }}.*" && pip freeze

      - name: Run sklearn tests with coverage
        if: matrix.sklearn-version != '1.8'
        run: |
            pytest --durations=10 \
              --ignore=unittests/builder/oxs \
              --ignore=unittests/reference/test__inference_session_torch.py \
              --ignore=unittests/reference/test_backend_torch_reference_evaluator.py \
              --ignore=unittests/reference/test_onnxruntime_evaluator.py \
              --ignore=unittests/reference/test_torch_reference_evaluator.py \
              --ignore=unittests/xoptim/test_torch_untrained_models.py \
              --ignore=unittests/tensorflow \
              --ignore=unittests/torch

      - name: Run sklearn tests with coverage
        if: matrix.sklearn-version == '1.8'
        run: |
            pytest --cov=yobx --cov-report=xml --durations=10 \
              --ignore=unittests/builder/oxs \
              --ignore=unittests/reference/test__inference_session_torch.py \
              --ignore=unittests/reference/test_backend_torch_reference_evaluator.py \
              --ignore=unittests/reference/test_onnxruntime_evaluator.py \
              --ignore=unittests/reference/test_torch_reference_evaluator.py \
              --ignore=unittests/xoptim/test_torch_untrained_models.py \
              --ignore=unittests/tensorflow \
              --ignore=unittests/torch

      - name: Upload coverage to Codecov
        if: matrix.sklearn-version == '1.8'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: sklearn
