name: tensorflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 4 * * *"

jobs:
  tensorflow_tests:
    name: tensorflow (ubuntu-latest, py${{ matrix.python-version }}, tf-${{ matrix.tensorflow-version }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
        tensorflow-version: ["2.20"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -e ".[dev]"

      - name: Install TensorFlow ${{ matrix.tensorflow-version }}
        run: pip install "tensorflow==${{ matrix.tensorflow-version }}.*" && pip freeze

      - name: Run sklearn tests with coverage
        if: matrix.sklearn-version == '1.8'
        run: |
            pytest --cov=yobx --cov-report=xml --durations=10 \
              --ignore=unittests/builder/oxs \
              --ignore=unittests/helpers/test_patch_helper.py \
              --ignore=unittests/reference/test__inference_session_torch.py \
              --ignore=unittests/reference/test_backend_torch_reference_evaluator.py \
              --ignore=unittests/reference/test_onnxruntime_evaluator.py \
              --ignore=unittests/reference/test_torch_reference_evaluator.py \
              --ignore=unittests/xoptim/test_untrained_models.py \
              --ignore=unittests/sklearn \
              --ignore=unittests/torch

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: tensorflow
