name: ci-8-transformers

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 3 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  transformers_dev:
    name: tr-dev (ubuntu-latest, py3.13, transformers-dev, torch-nightly)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install nightly pytorch
        run: pip install --pre --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu
      - name: Install development version of transformers
        run: pip install git+https://github.com/huggingface/transformers.git
      - name: Install dependencies
        run: pip install -e ".[dev,torch,transformers]"
      - name: pip freeze
        run: pip freeze
      - name: Run tests
        run: pytest --durations=10 unittests/torch --ignore=unittests/torch/interpreter/test_onnx_export_common_methods.py
