name: ci-3-tensorflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 4 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tensorflow_tests:
    name: tensorflow (ubuntu-latest, py${{ matrix.python-version }}, tf-${{ matrix.tensorflow-version }}, jax-${{ matrix.jax-version }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
        jax-version: ["0.9", "0.10"]
        tensorflow-version: ["2.20", "2.21"]
        exclude:
          - jax-version: "0.9"
            tensorflow-version: "2.21"
          - jax-version: "0.10"
            tensorflow-version: "2.20"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tensorflow==${{ matrix.tensorflow-version }} jax==${{ matrix.jax-version }}
        run: pip install "tensorflow==${{ matrix.tensorflow-version }}.*" "jax==${{ matrix.jax-version }}"

      - name: Install dependencies
        run: pip install -e ".[dev,tensorflow]"

      - name: Install tensorflow==${{ matrix.tensorflow-version }} jax==${{ matrix.jax-version }} again
        run: pip install "tensorflow==${{ matrix.tensorflow-version }}.*" "jax==${{ matrix.jax-version }}"

      - name: Run tensorflow tests with coverage
        run: |
            pytest --cov=yobx --cov-report=xml --durations=10 \
              --ignore=unittests/reference/test__inference_session_torch.py \
              --ignore=unittests/reference/test_backend_torch_reference_evaluator.py \
              --ignore=unittests/reference/test_torch_onnxruntime_evaluator.py \
              --ignore=unittests/reference/test_torch_reference_evaluator.py \
              --ignore=unittests/parity \
              --ignore=unittests/sklearn \
              --ignore=unittests/sql \
              --ignore=unittests/torch

      - name: Parity with tf2onnx
        run: |
          pip install tf2onnx
          pytest --durations=10 unittests/parity/with_tf2onnx

      - name: Parity with jax2onnx
        run: |
          pip install jax2onnx
          pytest --durations=10 unittests/parity/with_jax2onnx

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: tensorflow
