name: Coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  coverage:
    name: coverage (ubuntu-latest, py3.13)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install nightly pytorch
        run: pip install --pre --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu

      - name: Install dependencies
        run: pip install -e ".[dev,docs,torch]"

      - name: pip freeze
        run: pip freeze

      - name: Run tests with coverage
        run: pytest --cov=yobx --cov-report=xml --durations=10

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
