name: tensorflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 4 * * *"

jobs:
  tensorflow_tests:
    name: tf-tests (ubuntu-latest, py${{ matrix.python-version }}, tf-${{ matrix.tensorflow-version }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
        tensorflow-version: ["2.18"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -e ".[dev]"

      - name: Install TensorFlow ${{ matrix.tensorflow-version }}
        run: pip install "tensorflow==${{ matrix.tensorflow-version }}.*" && pip freeze

      - name: Run TensorFlow tests
        run: pytest unittests/tensorflow --durations=10
