name: Tests with no options (no torch, ...)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  no_torch_tests:
    name: no options tests (${{ matrix.os }}, py${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: pip install -e .

      - name: Install pytest
        run: pip install pytest

      - name: pip freeze
        run: pip freeze

      - name: Run tests (no torch)
        run: |
          pytest --durations=10 \
            --ignore=unittests/torch \
            --ignore=unittests/helpers/test_mini_onnx_builder.py \
            --ignore=unittests/helpers/test_patch_helper.py \
            --ignore=unittests/reference/test__inference_session.py \
            --ignore=unittests/reference/test_backend_torch_reference_evaluator.py \
            --ignore=unittests/reference/test_onnxruntime_evaluator.py \
            --ignore=unittests/reference/test_runtime_info.py \
            --ignore=unittests/reference/test_torch_reference_evaluator.py \
            --ignore=unittests/xoptim/test_untrained_models.py
