name: Torch Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 4 * * *"

jobs:
  torch_tests:
    name: torch tests (ubuntu-latest, py3.12, torch-nightly, transformers-${{ matrix.transformers-version }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        transformers-version: ["4.49", "4.55", "4.57", "5.2"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install -e ".[dev,docs,torch]"
      - name: Install transformers ${{ matrix.transformers-version }}
        run: pip install transformers==${{ matrix.transformers-version }}
      - name: Install nightly pytorch
        run: pip install --pre --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu
      - name: pip freeze
        run: pip freeze
      - name: Run tests
        run: pytest unittests/torch --durations=10
