name: Transformers Dev

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 3 * * *"

jobs:
  transformers_dev:
    name: transformers dev (ubuntu-latest, py3.12, torch-nightly, transformers-dev)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install nightly pytorch
        run: pip install --pre --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu
      - name: Install development version of transformers
        run: pip install git+https://github.com/huggingface/transformers.git
      - name: Install dependencies
        run: pip install -e ".[dev,docs,torch]"
      - name: pip freeze
        run: pip freeze
      - name: Run tests
        run: pytest --durations=10
